### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by igoforth** [YoSTEALTH/Dynamic-Import#2]
Hey! I really like the idea of this, and I'm currently doing some experiments with it. I also appreciate your work on the Python wrapper for Liburing.

My current project has the following structure:

`__init__.py`
```python
def main():
    pass
```

`__main__.py`
```python
from __init__ import main

main()
```

I then pack it into a pyz and run like `python Package.pyz`. Are there any plans to support this use-case?

Thanks!

**Comment by YoSTEALTH** [comment]
I am glad you are enjoying Dynamic Import and Liburing :)

It should work if you have package like so:

```python
# ./package/__init__.py
from dynamic_import import importer


importer()


def main():
    print('main() called')
```

```python
# ./package/pyz/__main__.py
from package import main


main()
```
Now you should be able to run it like so:
``` python
python3 -m package.pyz
# main() called
```

Rather than calling `from __init__ import main` you would call `from package import main`.

**Comment by igoforth** [comment]
> I am glad you are enjoying Dynamic Import and Liburing :)
> 
> It should work if you have package like so:
> 
> ```python
> # ./package/__init__.py
> from dynamic_import import importer
> 
> 
> importer()
> 
> 
> def main():
>     print('main() called')
> ```
> 
>  ```python
> # ./package/pyz/__main__.py
> from package import main
> 
> 
> main()
> ```
> 
> Now you should be able to run it like so:
> 
> ```python
> python3 -m package.pyz
> # main() called
> ```
> 
> Rather than calling `from __init__ import main` you would call `from package import main`.

Thanks! I’ll close as completed. I’m looking forward to where it goes.
